name: "CI Workflow"
on:
    push:
    pull_request:
      branches:
        - dev
        - main
jobs:
  build:
    name: Build OS
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout php
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: node install
        run:
          npm install
      - name: build the app
        run:
          npm build